FROM node:20-alpine

# задать рабоч директорию
WORKDIR /app

COPY frontend/package.json .
COPY .env .
COPY frontend/package-lock.json .

RUN npm install

COPY frontend/ .

EXPOSE 3000

CMD ["npm", "start"]