spring:
  application:
    name: aws

  datasource:
    url: ${DB_URL}
    # url: jdbc:postgresql://db_aws_host:5433/dbaws
    # url: jdbc:postgresql://localhost:5433/dbaws
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    flyway:
      baselineOnMigrate: true

