spring:
  application:
    name: aws

  datasource:
    url: jdbc:postgresql://db_aws_host:5433/dbaws
#    url: jdbc:postgresql://localhost:5433/dbaws
    username: postgres
    password: 1

    flyway:
      baselineOnMigrate: true

